#include <unordered_map>
#include <vector>
#include <string>

namespace  {
    class Event {
    public:
        inline static std::unordered_map<std::string, std::vector<std::string>> EventConstraints = {
		{ "ActiveAxes", {  } }, 
		{ "ActuatorState", { "ACTIVE","INACTIVE" } }, 
		{ "Alarm", {  } }, 
		{ "AssetChanged", {  } }, 
		{ "AssetRemoved", {  } }, 
		{ "Availability", { "AVAILABLE","UNAVAILABLE" } }, 
		{ "AxisCoupling", { "TANDEM","SYNCHRONOUS","MASTER","SLAVE" } }, 
		{ "AxisFeedrateOverride", {  } }, 
		{ "AxisInterlock", { "ACTIVE","INACTIVE" } }, 
		{ "AxisState", { "HOME","TRAVEL","PARKED","STOPPED" } }, 
		{ "Block", {  } }, 
		{ "BlockCount", {  } }, 
		{ "ChuckInterlock", { "ACTIVE","INACTIVE" } }, 
		{ "ChuckState", { "OPEN","CLOSED","UNLATCHED" } }, 
		{ "Code", {  } }, 
		{ "CompositionState", {  } }, 
		{ "ControllerMode", { "AUTOMATIC","MANUAL","MANUAL_DATA_INPUT","SEMI_AUTOMATIC","EDIT","FEED_HOLD" } }, 
		{ "ControllerModeOverride", { "ON","OFF" } }, 
		{ "CoupledAxes", {  } }, 
		{ "DateCode", {  } }, 
		{ "DeviceUuid", {  } }, 
		{ "Direction", { "CLOCKWISE","COUNTER_CLOCKWISE","POSITIVE","NEGATIVE" } }, 
		{ "DoorState", { "OPEN","CLOSED","UNLATCHED" } }, 
		{ "EmergencyStop", { "ARMED","TRIGGERED" } }, 
		{ "EndOfBar", { "YES","NO" } }, 
		{ "EquipmentMode", { "ON","OFF" } }, 
		{ "Execution", { "READY","ACTIVE","INTERRUPTED","FEED_HOLD","STOPPED","OPTIONAL_STOP","PROGRAM_STOPPED","PROGRAM_COMPLETED","WAIT","PROGRAM_OPTIONAL_STOP" } }, 
		{ "FunctionalMode", { "PRODUCTION","SETUP","TEARDOWN","MAINTENANCE","PROCESS_DEVELOPMENT" } }, 
		{ "Hardness", {  } }, 
		{ "Line", {  } }, 
		{ "LineLabel", {  } }, 
		{ "LineNumber", {  } }, 
		{ "Material", {  } }, 
		{ "MaterialLayer", {  } }, 
		{ "Message", {  } }, 
		{ "OperatorId", {  } }, 
		{ "PalletId", {  } }, 
		{ "PartCount", {  } }, 
		{ "PartDetect", { "PRESENT","NOT_PRESENT" } }, 
		{ "PartId", {  } }, 
		{ "PartNumber", {  } }, 
		{ "PathFeedrateOverride", {  } }, 
		{ "PathMode", { "INDEPENDENT","MASTER","SYNCHRONOUS","MIRROR" } }, 
		{ "PowerState", { "ON","OFF" } }, 
		{ "PowerStatus", { "ON","OFF" } }, 
		{ "ProcessTime", {  } }, 
		{ "Program", {  } }, 
		{ "ProgramComment", {  } }, 
		{ "ProgramEdit", { "ACTIVE","READY","NOT_READY" } }, 
		{ "ProgramEditName", {  } }, 
		{ "ProgramHeader", {  } }, 
		{ "ProgramLocation", {  } }, 
		{ "ProgramLocationType", { "LOCAL","EXTERNAL" } }, 
		{ "ProgramNestLevel", {  } }, 
		{ "RotaryMode", { "SPINDLE","INDEX","CONTOUR" } }, 
		{ "RotaryVelocityOverride", {  } }, 
		{ "SerialNumber", {  } }, 
		{ "SpindleInterlock", { "ACTIVE","INACTIVE" } }, 
		{ "ToolAssetId", {  } }, 
		{ "ToolGroup", {  } }, 
		{ "ToolId", {  } }, 
		{ "ToolNumber", {  } }, 
		{ "ToolOffset", {  } }, 
		{ "User", {  } }, 
		{ "Variable", {  } }, 
		{ "WaitState", { "POWERING_UP","POWERING_DOWN","PART_LOAD","PART_UNLOAD","TOOL_LOAD","TOOL_UNLOAD","MATERIAL_LOAD","MATERIAL_UNLOAD","SECONDARY_PROCESS","PAUSING","RESUMING" } }, 
		{ "Wire", {  } }, 
		{ "WorkholdingId", {  } }, 
		{ "WorkOffset", {  } }, 
		{ "OperatingSystem", {  } }, 
		{ "Firmware", {  } }, 
		{ "Application", {  } }, 
		{ "Library", {  } }, 
		{ "Hardware", {  } }, 
		{ "Network", {  } }, 
		{ "Rotation", {  } }, 
		{ "Translation", {  } }, 
		{ "ProcessKindId", {  } }, 
		{ "PartStatus", { "PASS","FAIL" } }, 
		{ "AlarmLimit", {  } }, 
		{ "ProcessAggregateId", {  } }, 
		{ "PartKindId", {  } }, 
		{ "AdapterURI", {  } }, 
		{ "DeviceRemoved", {  } }, 
		{ "DeviceChanged", {  } }, 
		{ "SpecificationLimit", {  } }, 
		{ "ConnectionStatus", { "CLOSED","LISTEN","ESTABLISHED" } }, 
		{ "AdapterSoftwareVersion", {  } }, 
		{ "SensorAttachment", {  } }, 
		{ "ControlLimit", {  } }, 
		{ "DeviceAdded", {  } }, 
		{ "MTConnectVersion", {  } }, 
		{ "ProcessOccurrenceId", {  } }, 
		{ "PartGroupId", {  } }, 
		{ "PartUniqueId", {  } }, 
		{ "ActivationCount", {  } }, 
		{ "DeactivationCount", {  } }, 
		{ "TransferCount", {  } }, 
		{ "LoadCount", {  } }, 
		{ "PartProcessingState", { "NEEDS_PROCESSING","IN_PROCESS","PROCESSING_ENDED","PROCESSING_ENDED_COMPLETE","PROCESSING_ENDED_STOPPED","PROCESSING_ENDED_ABORTED","PROCESSING_ENDED_LOST","PROCESSING_ENDED_SKIPPED","PROCESSING_ENDED_REJECTED","WAITING_FOR_TRANSIT","IN_TRANSIT","TRANSIT_COMPLETE" } }, 
		{ "ProcessState", { "INITIALIZING","READY","ACTIVE","COMPLETE","INTERRUPTED","ABORTED" } }, 
		{ "ValveState", { "OPEN","OPENING","CLOSED","CLOSING" } }, 
		{ "LockState", { "LOCKED","UNLOCKED" } }, 
		{ "UnloadCount", {  } }, 
		{ "CycleCount", {  } }, 
		{ "OperatingMode", { "AUTOMATIC","MANUAL","SEMI_AUTOMATIC" } }, 
		{ "AssetCount", {  } }, 
		{ "MaintenanceList", {  } }, 
		{ "FixtureId", {  } }, 
		{ "PartCountType", { "EACH","BATCH" } }, 
		{ "ClockTime", {  } }, 
		{ "NetworkPort", {  } }, 
		{ "HostName", {  } }, 
		{ "LeakDetect", { "DETECTED","NOT_DETECTED" } }, 
		{ "BatteryState", { "CHARGED","CHARGING","DISCHARGING","DISCHARGED" } }, 
		{ "FeaturePersisitentId", {  } }, 
		{ "SensorState", {  } }, 
		{ "ComponentData", {  } }, 
		{ "WorkOffsets", {  } }, 
		{ "ToolOffsets", {  } }, 
		{ "FeatureMeasurement", {  } }, 
		{ "CharacteristicPersistentId", {  } }, 
		{ "MeasurementType", {  } }, 
		{ "MeasurementValue", {  } }, 
		{ "MeasurementUnits", {  } }, 
		{ "CharacteristicStatus", { "PASS","FAIL","REWORK","SYSTEM_ERROR","INDETERMINATE","NOT_ANALYZED","BASIC_OR_THEORETIC_EXACT_DIMENSION","UNDEFINED" } }, 
		{ "UncertaintyType", { "COMBINED","MEAN" } }, 
		{ "Uncertainty", {  } }, 
		{ "AlarmLimits", {  } }, 
		{ "ControlLimits", {  } }, 
		{ "SpecificationLimits", {  } }, 
		{ "ToolCuttingItem", {  } }, 
		{ "LocationAddress", {  } }, 
		{ "PowerSource", {  } }
        };
    };

    // No need to define Constraints outside the class in C++17 or later
}
